# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Jason Chow
title: Computational Cognitive Psychologist
email: jason.k.chow@vanderbilt.edu
website: https://jasonc.how

# Dark Mode (true/false/never)
darkmode: never

# Social links
# twitter_username: facespics
github_username:  jasonkchow
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jameswgrant
# linkedin_username: jameswgrant
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0001-5439-471X

# Additional icon links
additional_links:
- title: Google Scholar
  icon: fas fa-book
  url: https://scholar.google.com/citations?user=dxEzLKAAAAAJ&hl=en
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, I study individual differences.

content:
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Vanderbilt University
        caption: 2018 - Present
        sub_title: PhD Psychology
        description: | # this will include new lines to allow paragraphs
          Coadvised and stuff. 
      - layout: left
        title: University of Toronto
        caption: 2014 - 2018
        sub_title: BS Honors Psychology
        description: | # this will include new lines to allow paragraphs
          Undergrad stuff

  - title: Research Interests
    layout: list
    content: 
      - layout: top-middle
        title: Individual differences in object recognition ability
        description: | # this will include new lines to allow paragraphs
          <div style="text-align:center"><img src="https://cdn.discordapp.com/emojis/1091129552044052590.webp?size=96&quality=lossless" /></div>

          In this line of research, I have developed completely new tests of 
          object recognition ability, applying psychometrics techniques to 
          confidently measure this ability in haptic and auditory perception. Using
          multivariate statistical techniques like confirmatory factor analysis, I 
          found that visual and haptic object recognition share about 25% of their
          variance. Interestingly, between visual and auditory object recognition 
          ability, there was an almost perfect correlation across modalities. The 
          robust relationships remain even when controlling for possible third 
          factors like general intelligence, working memory, and low-level visual 
          ability. These findings suggests that object recognition ability taps into 
          common perceptual mechanisms that extends across modalities.  

          **Representative Publications:**
          * **Chow, J. K.**, Palmeri, T. J., & Gauthier, I. (2022). Haptic object 
          recognition based on shape relates to visual object recognition ability. 
          *Psychological Research*, 86, 1262–1273 
          https://doi.org/10.1007/s00426-021-01560-z
          * **Chow, J.K.**, Palmeri, T. J., Pluck, G., & Gauthier, I. (2023). 
          Evidence for an amodal domain general object recognition ability. 
          *Manuscript under review*
      - layout: top-middle
        title: Modeling Individual Differences in Perception with DNNs
        description: | # this will include new lines to allow paragraphs
          We know that there are reliable individual differences in perceptual 
          abilities but why they exist remains elusive. I am interested in using 
          the latest deep neural networks to model individual differences and ask
          what factors best account for these differences. As modeling individual
          differences with deep neural networks is a relatively new approach, I have
          worked to determine the best ways to measure differences between deep 
          neural networks, directly comparing similarity metrics used in machine
          learning, psychology, and neuroscience. In parallel, I have begun work on
          determining which factors in deep neural networks are the best to 
          manipulate when the goal is to model individual differences. To do this, I
          sampled from a large space of deep neural networks to efficiently test 
          which combination of factors result in the most consistent variations. 

          **Representative Publications:**
          * **Chow, J.** & Palmeri, T. (2022). Manipulating and Measuring Variation 
          in DNN Representations. Poster presented at: *2022 Conference on Cognitive 
          Computational Neuroscience*; Aug 2022; San Francisco, CA

  - title: Side Projects
    layout: list # Type of content section (list/text)
    content:
      - layout: top
        title: Raided.pro
        caption: 2018 - 2023 [Expected]
        sub_title: PhD Psychology
        link: https://github.com/Raided-pro
        link_text: Github Organization Link
        additional_links:
          - title: Link 1
            icon: fas fa-puzzle-piece
            url: https://andrexia.com/
          - title: Link 2
            icon: fas fa-code
            url: https://observablehq.com/@jasonkchow
        quote: >
          Quote thingie
        description: | # this will include new lines to allow paragraphs
          Coadvised and stuff. 

      - layout: top-middle
        title: University of Toronto
        caption: 2014 - 2018
        sub_title: BS Honors Psychology
        description: | # this will include new lines to allow paragraphs
          Undergrad stuff   

      - layout: top-right
        title: University of Toronto
        caption: 2014 - 2018
        sub_title: BS Honors Psychology
        description: | # this will include new lines to allow paragraphs
          Undergrad stuff   

# Footer
footer_show_references: false
# references_title: https://jasonc.how/pdfs/CV-JasonKChow.pdf

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
